#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.ael/.ael.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.ael/battery.profile /data/.ael/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.ael/balanced.profile /data/.ael/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.ael/performance.profile /data/.ael/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
